### ISSUE TITLE
Bulk-request Players

### ISSUE THREAD

**Issue by thewilloftheshadow** [Geekid812/wolvesville-api#1]
A way to bulk-request multiple players without having to request each one from the API would be useful for my use case.
I am requesting about 10 players at a time to check them, and right now I'm toeing very close to that 10/min limit doing that.
I could see this either as passing multiple ids separated by commas or another endpoint to do that.

**Comment by Geekid812** [comment]
At the moment querying a player makes around 4 requests / player to the upstream server to piece out together the profile (player info, badges, clan, etc.). Perhaps bulk requests could be possible, but they would need to have trimmed data so that we only make 1/2 requests / player. That should make it possible to have bulk-requests of up to 10/15 players.

**Comment by Geekid812** [comment]
Implemented in 0.3.0.
